title: Test
markdown: kramdown

# for atom feed
author:
  name: Dylan Davidson
  email: test

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-analytics

collections_dir: all_collections
collections:
  posts:
    output: true

jekyll_analytics:
  Piwik:                    # Add, if you want to track with Piwik
    url: dylandavids0n.piwik.pro  # Required - url to Piwik installation without trailing /
    siteId: "93e358f1-d9bc-45a0-9668-788a335b88ca"          # Required - replace with your Piwik site id (Write id as string)

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
